### PR TITLE
First crack at an update to Spago

### PR DESCRIPTION
**Pull request by emiel**
I spent some time this evening with chapter 2 & 3 to see about a rewrite to use spago over pulp/psc-package. Chapter 2 is the most work so far because that is all about setting up the tooling.

This is a work in progress but wanted to go ahead and create a PR to let ppl know I'm working on this a bit. Please don't merge just yet. ;)

Some open issues that warrant some feedback:
* The invocation of `spago init` already produces a Main.purs file... Replacing it with the suggested code emits warnings. Would be nice not to spew warnings just yet...

* Would be nice to provide the HTML snippet to include the `index.js`.

* Update for latest PSCi commands/output, `:reset` command not available... use `:clear`?

* spago build emits CommonJS by default... the current text makes it seem like
  it is something special.

* I read somewhere that for apps you use spago but for libs its still  pulp/bower...

* Should we go ahead and include the a `test/Main.purs` file for the exercises?

### CODE REVIEW

**Comment by dwhitney** [comment]
Awesome! Add a comment to let me know when it's ready for review!

**Comment by dwhitney** [comment]
Just read your comments. I'll provide feedback in another comment momentarily

**Comment by dwhitney** [comment]
> The invocation of spago init already produces a Main.purs file... Replacing it with the suggested code emits warnings. Would be nice not to spew warnings just yet...

Yeah, I agree, but people trying Purescript will have enough programming experience to understand why the warning exists. I think what ever you decide in this case will be fine.

> Would be nice to provide the HTML snippet to include the index.js.

I think it's meant to be run with node, but yeah this would be cool. If you walk them through how to make this work with `parcel`, I think you've basically helped someone setup a standard/great development environment.

> Update for latest PSCi commands/output, :reset command not available... use :clear?

I know literally nothing about psci.

> spago build emits CommonJS by default... the current text makes it seem like it is something special.

This is worth explaining! It certainly makes the process of setting up a dev environment pretty simple. Personally once I understood this, it was very simple to make Purescript play nicely with React Native.

> I read somewhere that for apps you use spago but for libs its still pulp/bower...

Pursuit requires that a library exist in the bower repo and start with the names `purescript-`. pulp has the necessary machinery to upload the library to Pursuit, so that's why people still use those tools. I suspect library builders are still using spago but including `packages.dhall` and `spago.dhall` in their `.gitignore`. I have one library on Pursuit and that's what I have done. I'm sure replacing bower and pulp is on the spago roadmap, but hasn't been done yet. They've made a lot of progress (amazing progress!), so I wouldn't be surprised if that changed in the near future.

> Should we go ahead and include the a test/Main.purs file for the exercises?

I think it should be left out if it does nothing.

**Comment by colinwahl** [comment]
> * Should we go ahead and include the a `test/Main.purs` file for the exercises?

I'd agree that the test file should be left out if it does nothing, but I was just looking through spago issues and saw https://github.com/spacchetti/spago/issues/383, which causes an error to be thrown when `spago test` is run with no test directory. 

I know it's a bit weird to have an empty test file for the exercises, but I feel like (at least until the issue is resolved) it should exist just so that users aren't presented with this error when if they happen to run `spago test`.

**Comment by dwhitney** [comment]
@emiel thanks so much for working this!

**Comment by milesfrain** [comment]
> This is a work in progress but wanted to go ahead and create a PR to let ppl know I'm working on this a bit. Please don't merge just yet. ;)

I think this looks really good so far, and merging any chapters (even if still if not perfect yet) would likely be much more helpful to new users than the currently fragmented documentation. Maybe we can add a disclaimer at the beginning of some chapters that are still being heavily edited.

This is day 1 with PureScript for me, and I ended up going through a total of five setup guides in the following order.
* The standalone [Getting Started](https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md) guide
* The Getting Started chapter of the main book by paf31
* The Getting Started chapter of dwhitney's fork
* The [2019 tooling thread](https://discourse.purescript.org/t/recommended-tooling-for-purescript-applications-in-2019/948/10)
* The Getting Started chapter of the emiel's fork

Hopefully we can start consolidating this documentation sooner than later in order to make the learning process smoother for upcoming new users.

**Comment by dwhitney** [comment]
@emiel do you think your edits are ready for merging?

**Comment by emiel** [comment]
@milesfrain: Thanks for sharing your experiences. I'm in the same boat and still getting familiar with the language and tooling. I'm trying to contribute a bit by reviewing the book as I go along. From what I gathered spago is attaining the status of a decent replacement for at least pulp and psc-package. I decided to try and work through the book using spago and updating it as I go along. Still a work in progress so please be patient.

@dwhitney: Thanks for giving me another nudge. I worked through a few more chapters in a hurry just to see what I'm up against. I'm doing the exercises as I go along so I'm a bit slow going. There are a couple of things I ran into that I can't tackle just yet or have doubts about.

- Chapter 8: AffJax is not installable under spago (See: purescript/package-sets#507)
- Chapter 10: Is psc-bundle still a thing?
- Chapter 11: Port from Eff to Effect. The whole chapter needs to be reviewed in addition to the exercise. I'm not up for it yet.

I'd prefer not to merge until all chapters have been tackled. Readers would be quite surprised when the tooling changes in the middle of the book. Once all chapters are done it would be nice to have some more reviewers from the community. Please be patient. :)

**Comment by nickcernis** [comment]
Thanks for these updates!

Might be worth changing `pulp build` to `spago build` in chapter 1 too:

```
Commands which should be typed at the command line will be preceded by a dollar symbol:

$ pulp build
```

That `pulp build` will be the first (and only) time new readers encounter 'pulp' after these changes are merged, so it might seem odd that pulp is never mentioned again for the rest of the book.

**Comment by milesfrain** [comment]
Are these all our options for resolving the missing `affjax` dependency issue in chapter 8?
* Wait for bugfix
* Help with bugfix
* Edit `packages.dhall` to use `affjax v8.0.0`. I tried this, but couldn't get it working.

**Comment by emiel** [comment]
@milesfrain: I guess so. I understand there is also another lib called "milkis" which is similar to "affjax". Might be something to look into but I have no experience in this area.

**Comment by dwhitney** [comment]
@emiel @milesfrain we can probably make a PR against the latest spago package set. I plan to look at this tonight and see if we can get this all merged.

**Comment by dwhitney** [comment]
I am reviewing this now. It'll take me some time because it's pretty big. AMAZING WORK!!

**Comment by dwhitney** [comment]
It looks good to me. I am going to merge this and then fix the affjax issue. I think this PR has getting to big to manage otherwise.

**Comment by dwhitney** [comment]
I've merged this and made a temporary fix for chapter 8 to get Affjax working. I will continue to review, but the PR was becoming so big that I didn't feel comfortable letting it go any longer. Thank you so much for the work you put in. I want to make an announcement to the various places (twitter discourse, reddit, etc.) on Monday and will make sure to highlight all of the contributors on this especially @emiel !

**Comment by emiel** [comment]
Good call @dwhitney. Great to have more people seeing these changes now. I'll create GH issues for any remaining todo items.

**Comment by f-f** [comment]
I just stumbled on this thread by accident, and wow, great work! Thanks @emiel, @dwhitney and everyone else involved ❤️

**Comment by dwhitney** [comment]
It was all @emiel!

**Pull request merged**
