### PR TITLE
Add missing unsafePartial import

### PR DESCRIPTION
**Pull request by tssm**

### CODE REVIEW

**Comment by dwhitney** [comment]
Hmm... I don't like the use of `unsafePartial` here. I am going to merge this PR, but perhaps we ought to rewrite the example without `unsafePartial`. The context of the section/chapter is lost on me. Have you got any suggestions since you read it more recently?

**Comment by tssm** [comment]
I agree. Actually `unsafePartial` is not explained at all. It appears for the first time under [Recursion on Arrays](https://github.com/dwhitney/purescript-book/blob/master/text/chapter4.md#recursion-on-arrays) and there's no details on why it's needed. If you want I could try to rewrite the examples and exercises to avoid it

**Comment by dwhitney** [comment]
Yeah that would be awesome! My suggestion would be to use `fromMaybe` with
a short explanation of that function, but do whatever you think is best

Thanks,
D

**Comment by tssm** [comment]
No problem! `unsafePartial` appears in chapter 5 too, and I guess it appears in other chapters as well. Would you prefer a PR for each chapter or just one?

**Comment by dwhitney** [comment]
one is good. Thanks so much!

**Pull request merged**
